defaults:
  - algorithm: ppo
  - env: math_env
  - rl: default
  - planner: default
  - model: plain_mlp
  - train: default
  - eval: default
  - robot: robot_4dof
  - disturbance: sensor_noise
  - _self_

ppo:
  total_updates: 200

sac:
  total_steps: 2_000_000

hydra:
  job:
    chdir: false
